# Generated by Django 3.1.5 on 2021-01-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='publicado',
            new_name='publicada',
        ),
    ]
